### ISSUE TITLE
[home-assistant] Energy statistics not available

### ISSUE THREAD

**Issue by Timple** [Arnold-n/P1P2Serial#27]
I wanted to add my heatpump to the energy dashboard but it was not in the dropdown list.

As requested per this link: https://www.home-assistant.io/more-info/statistics/ I know opened this issue pointing this project to this link: https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

Is the `state_class` something that can be communicated via mqtt?

**Comment by Arnold-n** [comment]
Thanks tim, hopefully this works in just released P1P2-bridge-esp8266 v0.9.18. Coding is done ad-hoc, as it will be coded differently in P1P2MQTT.

**Comment by Timple** [comment]
Great, thanks!

Would it make sense to attached these releases as binaries to the releases tab in github?

**Comment by Arnold-n** [comment]
Just did! Thanks for the suggestion.

**Comment by Timple** [comment]
Awesome!
I'll verify asap (which is two weeks unfortunately)

**Comment by Timple** [comment]
Works! Thanks 👍
