### ISSUE TITLE
Fallback hotspot doesn't stop if wifi is available again

### ISSUE THREAD

**Issue by Timple** [Arnold-n/P1P2Serial#68]
We just had a full power-outage. And the P1P2Serial device was booted way before my router was.

Therefor the fallback hotspot was enabled. However when the wifi was finally up, the hotspot stayed and the mqtt connection was (thus) not established.

Easily fixed by a powercycle of the heatpump. But next time I might not notice it and we go weeks without logging :slightly_smiling_face: 

So this is a minor, but might be easy to fix, dunno. Some frameworks provide such a hotspot fallback themselves (esphome).

**Comment by Arnold-n** [comment]
Timeout added in P1P2-bridge-esp8266 v0.9.34.

**Comment by Timple** [comment]
Awesome, thanks for all your efforts!
