### ISSUE TITLE
Invalid heat pump power measurement?

### ISSUE THREAD

**Issue by AlbrechtL** [Arnold-n/P1P2Serial#92]
Thanks for this great project and hardware!

I have a strange heat pump power measurement behavior (see graph below). The orange line are the numbers directly reported from the heat pump. The blue line are the numbers read from a smart power meter. The orange line should be a little bit lower than the blue line but it is the other way around. What is really strange is that sometimes the reported orange numbers are negative. Can it be that the heat pump power measurement is wrong?

![image](https://github.com/Arnold-n/P1P2Serial/assets/11171787/632331c7-477c-4498-984d-b17914757c22)

Firmware: 0.9.43
Daikin EHBX08DA9W

**Comment by Arnold-n** [comment]
You're welcome! I think I will rename Power_Heatpump to Heat_Produced_Heatpump as the name is confusing: the orange line is actually heat produced: flow*dT*0.0697, and it is really negative during defrosts.

**Comment by AlbrechtL** [comment]
Thanks for the clarification!

**Comment by Axelaar** [comment]
I updated to P1P2MQTT bridge v0.9.53 and P1P2Monitor v0.9.54 from versions 9.42.  In those versions Power_Heatpump was available, as the calculated value of the heat produced.  In that older version it was positive for heating, and negative for cooling.
The topic was listed under .../M/9/...
What is the equivalent for that topic in this new version?

**Comment by Arnold-n** [comment]
For answer see https://github.com/Arnold-n/P1P2MQTT/discussions/116
